version: "3.7"
services: 
  client:
    image: node:10.13-alpine
    command: sh -c "npm install -g react-scripts@4.0.3 && npm install && npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    